CountryTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: Country-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: N
    KeySchema:
      - AttributeName: id
        KeyType: HASH