service: atp-tour

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    TOURNAMENT_TABLE_NAME: ${self:custom.TournamentTable.name}
  iamRoleStatements:
    - ${file(iam/TournamentTableIAM.yml):TournamentTableIAM}

resources:
  Resources:
    TournamentTable: ${file(resources/TournamentTable.yml):TournamentTable}
  
functions:
  createTournament:
    handler: src/handlers/tournament/createTournament.handler
    events:
      - http:
          method: POST
          path: /tournament

  getTournament:
    handler: src/handlers/tournament/getTournament.handler
    events:
      - http:
          method: GET
          path: /tournament/{id}

  getTournaments:
    handler: src/handlers/tournament/getTournaments.handler
    events:
      - http:
          method: GET
          path: /tournament

custom:
  TournamentTable:
    name: !Ref TournamentTable
    arn: !GetAtt TournamentTable.Arn
  bundle:
    linting: false
