service:
  name: atp-tour

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    TOURNAMENT_TABLE_NAME: ${self:custom.TournamentTable.name}
  iamRoleStatements:
    - ${file(iam/TournamentIAM.yml):TournamentIAM}

resources:
  Resources:
    TournamentTable: $(file(resources/TournamentTable.yml):TournamentTable)
  
functions:
  hello:
    handler: src/handlers/hello.handler
    events:
      - http:
          method: GET
          path: /hello

custom:
  TournamentTable:
    name: !Ref TournamentTable
    arn: !GetAtt TournamentTable.Arn
  bundle:
    linting: false
